/*
  # Seed Minor Arcana - Cups Suit

  Inserts 14 Cups cards (Ace through King)
*/

INSERT INTO tarot_cards (id, name_en, name_it, arcana, suit, number, court, keywords_en, keywords_it, upright_meaning_en, upright_meaning_it, reversed_meaning_en, reversed_meaning_it) VALUES
(36, 'Ace of Cups', 'Asso di Coppe', 'minor', 'cups', 1, NULL,
  ARRAY['love', 'new relationships', 'compassion', 'creativity'],
  ARRAY['amore', 'nuove relazioni', 'compassione', 'creatività'],
  'Love, new relationships, compassion, creativity. Emotional beginnings.',
  'Amore, nuove relazioni, compassione, creatività. Inizi emotivi.',
  'Self-love, intuition, repressed emotions.',
  'Amor proprio, intuizione, emozioni represse.'),
(37, 'Two of Cups', 'Due di Coppe', 'minor', 'cups', 2, NULL,
  ARRAY['unified love', 'partnership', 'mutual attraction'],
  ARRAY['amore unificato', 'partnership', 'attrazione reciproca'],
  'Unified love, partnership, mutual attraction. Connection.',
  'Amore unificato, partnership, attrazione reciproca. Connessione.',
  'Self-love, break-ups, disharmony, distrust.',
  'Amor proprio, rotture, disarmonia, sfiducia.'),
(38, 'Three of Cups', 'Tre di Coppe', 'minor', 'cups', 3, NULL,
  ARRAY['celebration', 'friendship', 'creativity', 'collaborations'],
  ARRAY['celebrazione', 'amicizia', 'creatività', 'collaborazioni'],
  'Celebration, friendship, creativity, collaborations.',
  'Celebrazione, amicizia, creatività, collaborazioni.',
  'Independence, alone time, hardcore partying, gossip.',
  'Indipendenza, tempo da soli, eccessi, pettegolezzi.'),
(39, 'Four of Cups', 'Quattro di Coppe', 'minor', 'cups', 4, NULL,
  ARRAY['meditation', 'contemplation', 'apathy', 'reevaluation'],
  ARRAY['meditazione', 'contemplazione', 'apatia', 'rivalutazione'],
  'Meditation, contemplation, apathy, reevaluation.',
  'Meditazione, contemplazione, apatia, rivalutazione.',
  'Retreat, withdrawal, checking in for alignment.',
  'Ritiro, isolamento, verifica dell''allineamento.'),
(40, 'Five of Cups', 'Cinque di Coppe', 'minor', 'cups', 5, NULL,
  ARRAY['regret', 'failure', 'disappointment', 'pessimism'],
  ARRAY['rimpianto', 'fallimento', 'delusione', 'pessimismo'],
  'Regret, failure, disappointment, pessimism. Focusing on loss.',
  'Rimpianto, fallimento, delusione, pessimismo. Concentrarsi sulla perdita.',
  'Personal setbacks, self-forgiveness, moving on.',
  'Battute d''arresto personali, auto-perdono, andare avanti.'),
(41, 'Six of Cups', 'Sei di Coppe', 'minor', 'cups', 6, NULL,
  ARRAY['revisiting the past', 'childhood memories', 'innocence'],
  ARRAY['rivisitare il passato', 'ricordi d''infanzia', 'innocenza'],
  'Revisiting the past, childhood memories, innocence, joy.',
  'Rivisitare il passato, ricordi d''infanzia, innocenza, gioia.',
  'Living in the past, forgiveness, lacking playfulness.',
  'Vivere nel passato, perdono, mancanza di giocosità.'),
(42, 'Seven of Cups', 'Sette di Coppe', 'minor', 'cups', 7, NULL,
  ARRAY['opportunities', 'choices', 'wishful thinking', 'illusion'],
  ARRAY['opportunità', 'scelte', 'pensiero illusorio', 'illusione'],
  'Opportunities, choices, wishful thinking, illusion.',
  'Opportunità, scelte, pensiero illusorio, illusione.',
  'Alignment, personal values, overwhelmed by choices.',
  'Allineamento, valori personali, sopraffatto dalle scelte.'),
(43, 'Eight of Cups', 'Otto di Coppe', 'minor', 'cups', 8, NULL,
  ARRAY['disappointment', 'abandonment', 'withdrawal', 'escapism'],
  ARRAY['delusione', 'abbandono', 'ritiro', 'fuga'],
  'Disappointment, abandonment, withdrawal, escapism.',
  'Delusione, abbandono, ritiro, fuga.',
  'Trying one more time, indecision, aimless drifting.',
  'Provare ancora una volta, indecisione, vagare senza meta.'),
(44, 'Nine of Cups', 'Nove di Coppe', 'minor', 'cups', 9, NULL,
  ARRAY['contentment', 'satisfaction', 'gratitude', 'wish come true'],
  ARRAY['contentezza', 'soddisfazione', 'gratitudine', 'desiderio realizzato'],
  'Contentment, satisfaction, gratitude, wish come true.',
  'Contentezza, soddisfazione, gratitudine, desiderio realizzato.',
  'Inner happiness, materialism, dissatisfaction.',
  'Felicità interiore, materialismo, insoddisfazione.'),
(45, 'Ten of Cups', 'Dieci di Coppe', 'minor', 'cups', 10, NULL,
  ARRAY['divine love', 'blissful relationships', 'harmony', 'alignment'],
  ARRAY['amore divino', 'relazioni felici', 'armonia', 'allineamento'],
  'Divine love, blissful relationships, harmony, alignment.',
  'Amore divino, relazioni felici, armonia, allineamento.',
  'Disconnection, misaligned values, struggling relationships.',
  'Disconnessione, valori disallineati, relazioni difficili.'),
(46, 'Page of Cups', 'Fante di Coppe', 'minor', 'cups', NULL, 'page',
  ARRAY['creative opportunities', 'intuitive messages', 'curiosity'],
  ARRAY['opportunità creative', 'messaggi intuitivi', 'curiosità'],
  'Creative opportunities, intuitive messages, curiosity, possibility.',
  'Opportunità creative, messaggi intuitivi, curiosità, possibilità.',
  'New ideas, doubting intuition, creative blocks.',
  'Nuove idee, dubitare dell''intuizione, blocchi creativi.'),
(47, 'Knight of Cups', 'Cavaliere di Coppe', 'minor', 'cups', NULL, 'knight',
  ARRAY['creativity', 'romance', 'charm', 'imagination'],
  ARRAY['creatività', 'romanticismo', 'fascino', 'immaginazione'],
  'Creativity, romance, charm, imagination, beauty.',
  'Creatività, romanticismo, fascino, immaginazione, bellezza.',
  'Overactive imagination, unrealistic, jealous.',
  'Immaginazione iperattiva, irrealistico, geloso.'),
(48, 'Queen of Cups', 'Regina di Coppe', 'minor', 'cups', NULL, 'queen',
  ARRAY['compassion', 'calm', 'comfort', 'intuition'],
  ARRAY['compassione', 'calma', 'conforto', 'intuizione'],
  'Compassion, calm, comfort. Emotional security, intuitive.',
  'Compassione, calma, conforto. Sicurezza emotiva, intuitiva.',
  'Inner feelings, self-care, self-love, co-dependency.',
  'Sentimenti interiori, cura di sé, amor proprio, co-dipendenza.'),
(49, 'King of Cups', 'Re di Coppe', 'minor', 'cups', NULL, 'king',
  ARRAY['emotional balance', 'control', 'compassion', 'generosity'],
  ARRAY['equilibrio emotivo', 'controllo', 'compassione', 'generosità'],
  'Emotional balance, control, compassion, generosity.',
  'Equilibrio emotivo, controllo, compassione, generosità.',
  'Self-compassion, inner feelings, moodiness, emotionally manipulative.',
  'Auto-compassione, sentimenti interiori, lunaticità, manipolazione emotiva.')
ON CONFLICT (id) DO NOTHING;