/*
  # Seed Minor Arcana - Wands Suit

  Inserts 14 Wands cards (Ace through King)
*/

INSERT INTO tarot_cards (id, name_en, name_it, arcana, suit, number, court, keywords_en, keywords_it, upright_meaning_en, upright_meaning_it, reversed_meaning_en, reversed_meaning_it) VALUES
(22, 'Ace of Wands', 'Asso di Bastoni', 'minor', 'wands', 1, NULL,
  ARRAY['inspiration', 'new opportunities', 'growth', 'potential'],
  ARRAY['ispirazione', 'nuove opportunità', 'crescita', 'potenziale'],
  'Inspiration, new opportunities, growth, potential. A spark of creativity.',
  'Ispirazione, nuove opportunità, crescita, potenziale. Una scintilla di creatività.',
  'An emerging idea, lack of direction, distractions.',
  'Un''idea emergente, mancanza di direzione, distrazioni.'),
(23, 'Two of Wands', 'Due di Bastoni', 'minor', 'wands', 2, NULL,
  ARRAY['future planning', 'progress', 'decisions', 'discovery'],
  ARRAY['pianificazione', 'progresso', 'decisioni', 'scoperta'],
  'Future planning, progress, decisions, discovery. Looking ahead.',
  'Pianificazione futura, progresso, decisioni, scoperta. Guardare avanti.',
  'Fear of unknown, lack of planning, playing it safe.',
  'Paura dell''ignoto, mancanza di pianificazione, giocare sul sicuro.'),
(24, 'Three of Wands', 'Tre di Bastoni', 'minor', 'wands', 3, NULL,
  ARRAY['progress', 'expansion', 'foresight', 'overseas opportunities'],
  ARRAY['progresso', 'espansione', 'preveggenza', 'opportunità oltremare'],
  'Progress, expansion, foresight, overseas opportunities.',
  'Progresso, espansione, preveggenza, opportunità all''estero.',
  'Playing small, lack of foresight, unexpected delays.',
  'Giocare in piccolo, mancanza di preveggenza, ritardi inattesi.'),
(25, 'Four of Wands', 'Quattro di Bastoni', 'minor', 'wands', 4, NULL,
  ARRAY['celebration', 'joy', 'harmony', 'relaxation', 'homecoming'],
  ARRAY['celebrazione', 'gioia', 'armonia', 'relax', 'ritorno a casa'],
  'Celebration, joy, harmony, relaxation, homecoming.',
  'Celebrazione, gioia, armonia, relax, ritorno a casa.',
  'Personal celebration, inner harmony, conflict with others.',
  'Celebrazione personale, armonia interiore, conflitto con gli altri.'),
(26, 'Five of Wands', 'Cinque di Bastoni', 'minor', 'wands', 5, NULL,
  ARRAY['conflict', 'disagreements', 'competition', 'tension'],
  ARRAY['conflitto', 'disaccordi', 'competizione', 'tensione'],
  'Conflict, disagreements, competition, tension, diversity.',
  'Conflitto, disaccordi, competizione, tensione, diversità.',
  'Inner conflict, conflict avoidance, tension release.',
  'Conflitto interiore, evitamento del conflitto, rilascio della tensione.'),
(27, 'Six of Wands', 'Sei di Bastoni', 'minor', 'wands', 6, NULL,
  ARRAY['success', 'public recognition', 'progress', 'self-confidence'],
  ARRAY['successo', 'riconoscimento pubblico', 'progresso', 'fiducia in sé'],
  'Success, public recognition, progress, self-confidence.',
  'Successo, riconoscimento pubblico, progresso, fiducia in sé.',
  'Private achievement, personal definition of success, fall from grace.',
  'Successo privato, definizione personale di successo, caduta in disgrazia.'),
(28, 'Seven of Wands', 'Sette di Bastoni', 'minor', 'wands', 7, NULL,
  ARRAY['challenge', 'competition', 'protection', 'perseverance'],
  ARRAY['sfida', 'competizione', 'protezione', 'perseveranza'],
  'Challenge, competition, protection, perseverance. Standing your ground.',
  'Sfida, competizione, protezione, perseveranza. Mantenere la posizione.',
  'Exhaustion, giving up, overwhelmed.',
  'Esaurimento, arrendersi, sopraffazione.'),
(29, 'Eight of Wands', 'Otto di Bastoni', 'minor', 'wands', 8, NULL,
  ARRAY['movement', 'fast paced change', 'action', 'alignment'],
  ARRAY['movimento', 'cambiamento rapido', 'azione', 'allineamento'],
  'Movement, fast paced change, action, alignment, air travel.',
  'Movimento, cambiamento rapido, azione, allineamento, viaggi aerei.',
  'Delays, frustration, resisting change, internal alignment.',
  'Ritardi, frustrazione, resistere al cambiamento, allineamento interiore.'),
(30, 'Nine of Wands', 'Nove di Bastoni', 'minor', 'wands', 9, NULL,
  ARRAY['resilience', 'courage', 'persistence', 'test of faith'],
  ARRAY['resilienza', 'coraggio', 'persistenza', 'prova di fede'],
  'Resilience, courage, persistence, test of faith, boundaries.',
  'Resilienza, coraggio, persistenza, prova di fede, confini.',
  'Inner resources, struggle, overwhelm, defensive.',
  'Risorse interiori, lotta, sopraffazione, difensivo.'),
(31, 'Ten of Wands', 'Dieci di Bastoni', 'minor', 'wands', 10, NULL,
  ARRAY['burden', 'extra responsibility', 'hard work', 'completion'],
  ARRAY['fardello', 'responsabilità extra', 'duro lavoro', 'completamento'],
  'Burden, extra responsibility, hard work, completion.',
  'Fardello, responsabilità extra, duro lavoro, completamento.',
  'Doing it all, delegation, release.',
  'Fare tutto da soli, delegare, liberazione.'),
(32, 'Page of Wands', 'Fante di Bastoni', 'minor', 'wands', NULL, 'page',
  ARRAY['inspiration', 'ideas', 'discovery', 'limitless potential'],
  ARRAY['ispirazione', 'idee', 'scoperta', 'potenziale illimitato'],
  'Inspiration, ideas, discovery, limitless potential, free spirit.',
  'Ispirazione, idee, scoperta, potenziale illimitato, spirito libero.',
  'Newly-formed ideas, redirect your energy, self-limiting beliefs.',
  'Idee appena formate, reindirizzare l''energia, credenze auto-limitanti.'),
(33, 'Knight of Wands', 'Cavaliere di Bastoni', 'minor', 'wands', NULL, 'knight',
  ARRAY['energy', 'passion', 'inspired action', 'adventure'],
  ARRAY['energia', 'passione', 'azione ispirata', 'avventura'],
  'Energy, passion, inspired action, adventure, impulsiveness.',
  'Energia, passione, azione ispirata, avventura, impulsività.',
  'Passion project, haste, scattered energy, delays.',
  'Progetto passionale, fretta, energia dispersa, ritardi.'),
(34, 'Queen of Wands', 'Regina di Bastoni', 'minor', 'wands', NULL, 'queen',
  ARRAY['courage', 'confidence', 'independence', 'social butterfly'],
  ARRAY['coraggio', 'fiducia', 'indipendenza', 'farfalla sociale'],
  'Courage, confidence, independence, social butterfly, determination.',
  'Coraggio, fiducia, indipendenza, farfalla sociale, determinazione.',
  'Self-respect, self-confidence, introverted, re-establish sense of self.',
  'Rispetto di sé, fiducia in sé, introverso, ristabilire il senso di sé.'),
(35, 'King of Wands', 'Re di Bastoni', 'minor', 'wands', NULL, 'king',
  ARRAY['natural-born leader', 'vision', 'entrepreneur', 'honour'],
  ARRAY['leader nato', 'visione', 'imprenditore', 'onore'],
  'Natural-born leader, vision, entrepreneur, honour.',
  'Leader nato, visione, imprenditore, onore.',
  'Impulsiveness, haste, ruthless, high expectations.',
  'Impulsività, fretta, spietatezza, alte aspettative.')
ON CONFLICT (id) DO NOTHING;