/*
  # Seed Minor Arcana - Pentacles Suit

  Inserts 14 Pentacles cards (Ace through King)
*/

INSERT INTO tarot_cards (id, name_en, name_it, arcana, suit, number, court, keywords_en, keywords_it, upright_meaning_en, upright_meaning_it, reversed_meaning_en, reversed_meaning_it) VALUES
(64, 'Ace of Pentacles', 'Asso di Denari', 'minor', 'pentacles', 1, NULL,
  ARRAY['new financial opportunity', 'manifestation', 'abundance'],
  ARRAY['nuova opportunità finanziaria', 'manifestazione', 'abbondanza'],
  'New financial or career opportunity, manifestation, abundance.',
  'Nuova opportunità finanziaria o lavorativa, manifestazione, abbondanza.',
  'Lost opportunity, lack of planning, scarcity mindset.',
  'Opportunità persa, mancanza di pianificazione, mentalità di scarsità.'),
(65, 'Two of Pentacles', 'Due di Denari', 'minor', 'pentacles', 2, NULL,
  ARRAY['multiple priorities', 'time management', 'adaptability'],
  ARRAY['priorità multiple', 'gestione del tempo', 'adattabilità'],
  'Multiple priorities, time management, prioritization, adaptability.',
  'Priorità multiple, gestione del tempo, definizione delle priorità, adattabilità.',
  'Over-committed, disorganization, reprioritization.',
  'Troppi impegni, disorganizzazione, ridefinizione delle priorità.'),
(66, 'Three of Pentacles', 'Tre di Denari', 'minor', 'pentacles', 3, NULL,
  ARRAY['teamwork', 'collaboration', 'learning', 'implementation'],
  ARRAY['lavoro di squadra', 'collaborazione', 'apprendimento', 'implementazione'],
  'Teamwork, collaboration, learning, implementation.',
  'Lavoro di squadra, collaborazione, apprendimento, implementazione.',
  'Disharmony, misalignment, working alone.',
  'Disarmonia, disallineamento, lavorare da soli.'),
(67, 'Four of Pentacles', 'Quattro di Denari', 'minor', 'pentacles', 4, NULL,
  ARRAY['saving money', 'security', 'conservatism', 'scarcity'],
  ARRAY['risparmiare denaro', 'sicurezza', 'conservatorismo', 'scarsità'],
  'Saving money, security, conservatism, scarcity.',
  'Risparmiare denaro, sicurezza, conservatorismo, scarsità.',
  'Over-spending, greed, self-protection.',
  'Spendere troppo, avidità, auto-protezione.'),
(68, 'Five of Pentacles', 'Cinque di Denari', 'minor', 'pentacles', 5, NULL,
  ARRAY['financial loss', 'poverty', 'lack mindset', 'isolation'],
  ARRAY['perdita finanziaria', 'povertà', 'mentalità di mancanza', 'isolamento'],
  'Financial loss, poverty, lack mindset, isolation, worry.',
  'Perdita finanziaria, povertà, mentalità di mancanza, isolamento, preoccupazione.',
  'Recovery from financial loss, spiritual poverty, inner poverty.',
  'Recupero da perdita finanziaria, povertà spirituale, povertà interiore.'),
(69, 'Six of Pentacles', 'Sei di Denari', 'minor', 'pentacles', 6, NULL,
  ARRAY['giving', 'receiving', 'sharing wealth', 'generosity'],
  ARRAY['dare', 'ricevere', 'condividere la ricchezza', 'generosità'],
  'Giving, receiving, sharing wealth, generosity.',
  'Dare, ricevere, condividere la ricchezza, generosità.',
  'Self-care, unpaid debts, one-sided charity.',
  'Cura di sé, debiti non pagati, carità unilaterale.'),
(70, 'Seven of Pentacles', 'Sette di Denari', 'minor', 'pentacles', 7, NULL,
  ARRAY['long-term view', 'sustainable results', 'perseverance'],
  ARRAY['visione a lungo termine', 'risultati sostenibili', 'perseveranza'],
  'Long-term view, sustainable results, perseverance, investment.',
  'Visione a lungo termine, risultati sostenibili, perseveranza, investimento.',
  'Lack of long-term vision, limited success, impatience.',
  'Mancanza di visione a lungo termine, successo limitato, impazienza.'),
(71, 'Eight of Pentacles', 'Otto di Denari', 'minor', 'pentacles', 8, NULL,
  ARRAY['apprenticeship', 'repetitive tasks', 'mastery', 'skill development'],
  ARRAY['apprendistato', 'compiti ripetitivi', 'padronanza', 'sviluppo delle competenze'],
  'Apprenticeship, repetitive tasks, mastery, skill development.',
  'Apprendistato, compiti ripetitivi, padronanza, sviluppo delle competenze.',
  'Self-development, perfectionism, misdirected activity.',
  'Auto-sviluppo, perfezionismo, attività mal indirizzata.'),
(72, 'Nine of Pentacles', 'Nove di Denari', 'minor', 'pentacles', 9, NULL,
  ARRAY['abundance', 'luxury', 'self-sufficiency', 'financial independence'],
  ARRAY['abbondanza', 'lusso', 'autosufficienza', 'indipendenza finanziaria'],
  'Abundance, luxury, self-sufficiency, financial independence.',
  'Abbondanza, lusso, autosufficienza, indipendenza finanziaria.',
  'Self-worth, over-investment in work, hustling.',
  'Autostima, eccessivo investimento nel lavoro, affannarsi.'),
(73, 'Ten of Pentacles', 'Dieci di Denari', 'minor', 'pentacles', 10, NULL,
  ARRAY['wealth', 'financial security', 'family', 'long-term success'],
  ARRAY['ricchezza', 'sicurezza finanziaria', 'famiglia', 'successo a lungo termine'],
  'Wealth, financial security, family, long-term success, contribution.',
  'Ricchezza, sicurezza finanziaria, famiglia, successo a lungo termine, contributo.',
  'The dark side of wealth, financial failure or loss.',
  'Il lato oscuro della ricchezza, fallimento o perdita finanziaria.'),
(74, 'Page of Pentacles', 'Fante di Denari', 'minor', 'pentacles', NULL, 'page',
  ARRAY['manifestation', 'financial opportunity', 'skill development'],
  ARRAY['manifestazione', 'opportunità finanziaria', 'sviluppo delle competenze'],
  'Manifestation, financial opportunity, skill development.',
  'Manifestazione, opportunità finanziaria, sviluppo delle competenze.',
  'Lack of progress, procrastination, learn from failure.',
  'Mancanza di progresso, procrastinazione, imparare dal fallimento.'),
(75, 'Knight of Pentacles', 'Cavaliere di Denari', 'minor', 'pentacles', NULL, 'knight',
  ARRAY['hard work', 'productivity', 'routine', 'conservatism'],
  ARRAY['duro lavoro', 'produttività', 'routine', 'conservatorismo'],
  'Hard work, productivity, routine, conservatism.',
  'Duro lavoro, produttività, routine, conservatorismo.',
  'Self-discipline, boredom, feeling stuck, perfectionism.',
  'Auto-disciplina, noia, sentirsi bloccati, perfezionismo.'),
(76, 'Queen of Pentacles', 'Regina di Denari', 'minor', 'pentacles', NULL, 'queen',
  ARRAY['nurturing', 'practical', 'providing financially', 'working parent'],
  ARRAY['nutrimento', 'praticità', 'provvedere finanziariamente', 'genitore lavoratore'],
  'Nurturing, practical, providing financially, a working parent.',
  'Nutrimento, praticità, provvedere finanziariamente, genitore lavoratore.',
  'Financial independence, self-care, work-home conflict.',
  'Indipendenza finanziaria, cura di sé, conflitto lavoro-casa.'),
(77, 'King of Pentacles', 'Re di Denari', 'minor', 'pentacles', NULL, 'king',
  ARRAY['wealth', 'business', 'leadership', 'security', 'discipline'],
  ARRAY['ricchezza', 'affari', 'leadership', 'sicurezza', 'disciplina'],
  'Wealth, business, leadership, security, discipline, abundance.',
  'Ricchezza, affari, leadership, sicurezza, disciplina, abbondanza.',
  'Financially inept, obsessed with wealth and status, stubborn.',
  'Finanziariamente incapace, ossessionato da ricchezza e status, testardo.')
ON CONFLICT (id) DO NOTHING;