/*
  # Seed Tarot Cards

  Inserts all 78 tarot cards:
  - 22 Major Arcana (0-21)
  - 56 Minor Arcana (14 cards per suit x 4 suits)
*/

-- Major Arcana (22 cards)
INSERT INTO tarot_cards (id, name_en, name_it, arcana, suit, number, court, keywords_en, keywords_it, upright_meaning_en, upright_meaning_it, reversed_meaning_en, reversed_meaning_it) VALUES
(0, 'The Fool', 'Il Matto', 'major', NULL, 0, NULL, 
  ARRAY['beginnings', 'innocence', 'spontaneity', 'free spirit'],
  ARRAY['inizi', 'innocenza', 'spontaneità', 'spirito libero'],
  'New beginnings, innocence, spontaneity, a free spirit. Taking a leap of faith.',
  'Nuovi inizi, innocenza, spontaneità, spirito libero. Fare un salto nel vuoto.',
  'Holding back, recklessness, risk-taking without thought.',
  'Trattenersi, avventatezza, correre rischi senza riflettere.'),
(1, 'The Magician', 'Il Mago', 'major', NULL, 1, NULL,
  ARRAY['manifestation', 'resourcefulness', 'power', 'inspired action'],
  ARRAY['manifestazione', 'intraprendenza', 'potere', 'azione ispirata'],
  'Manifestation, resourcefulness, power, inspired action. You have all the tools you need.',
  'Manifestazione, intraprendenza, potere, azione ispirata. Hai tutti gli strumenti necessari.',
  'Manipulation, poor planning, untapped talents.',
  'Manipolazione, scarsa pianificazione, talenti inespressi.'),
(2, 'The High Priestess', 'La Papessa', 'major', NULL, 2, NULL,
  ARRAY['intuition', 'sacred knowledge', 'divine feminine', 'subconscious'],
  ARRAY['intuizione', 'conoscenza sacra', 'femminile divino', 'subconscio'],
  'Intuition, sacred knowledge, divine feminine, the subconscious mind.',
  'Intuizione, conoscenza sacra, femminile divino, mente subconscia.',
  'Secrets, disconnected from intuition, withdrawal.',
  'Segreti, disconnessione dall''intuizione, ritiro.'),
(3, 'The Empress', 'L''Imperatrice', 'major', NULL, 3, NULL,
  ARRAY['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
  ARRAY['femminilità', 'bellezza', 'natura', 'nutrimento', 'abbondanza'],
  'Femininity, beauty, nature, nurturing, abundance. Creative expression.',
  'Femminilità, bellezza, natura, nutrimento, abbondanza. Espressione creativa.',
  'Creative block, dependence on others, emptiness.',
  'Blocco creativo, dipendenza dagli altri, vuoto.'),
(4, 'The Emperor', 'L''Imperatore', 'major', NULL, 4, NULL,
  ARRAY['authority', 'establishment', 'structure', 'father figure'],
  ARRAY['autorità', 'stabilità', 'struttura', 'figura paterna'],
  'Authority, establishment, structure, a father figure. Taking control.',
  'Autorità, stabilità, struttura, figura paterna. Prendere il controllo.',
  'Domination, excessive control, lack of discipline.',
  'Dominazione, controllo eccessivo, mancanza di disciplina.'),
(5, 'The Hierophant', 'Il Papa', 'major', NULL, 5, NULL,
  ARRAY['spiritual wisdom', 'tradition', 'conformity', 'morality'],
  ARRAY['saggezza spirituale', 'tradizione', 'conformità', 'moralità'],
  'Spiritual wisdom, religious beliefs, conformity, tradition.',
  'Saggezza spirituale, credenze religiose, conformità, tradizione.',
  'Personal beliefs, freedom, challenging the status quo.',
  'Credenze personali, libertà, sfidare lo status quo.'),
(6, 'The Lovers', 'Gli Amanti', 'major', NULL, 6, NULL,
  ARRAY['love', 'harmony', 'relationships', 'values alignment', 'choices'],
  ARRAY['amore', 'armonia', 'relazioni', 'allineamento valori', 'scelte'],
  'Love, harmony, relationships, values alignment, choices.',
  'Amore, armonia, relazioni, allineamento dei valori, scelte.',
  'Self-love, disharmony, imbalance, misalignment of values.',
  'Amor proprio, disarmonia, squilibrio, disallineamento dei valori.'),
(7, 'The Chariot', 'Il Carro', 'major', NULL, 7, NULL,
  ARRAY['control', 'willpower', 'success', 'action', 'determination'],
  ARRAY['controllo', 'forza di volontà', 'successo', 'azione', 'determinazione'],
  'Control, willpower, success, action, determination. Moving forward.',
  'Controllo, forza di volontà, successo, azione, determinazione. Andare avanti.',
  'Self-discipline issues, opposition, lack of direction.',
  'Problemi di autodisciplina, opposizione, mancanza di direzione.'),
(8, 'Strength', 'La Forza', 'major', NULL, 8, NULL,
  ARRAY['strength', 'courage', 'persuasion', 'influence', 'compassion'],
  ARRAY['forza', 'coraggio', 'persuasione', 'influenza', 'compassione'],
  'Strength, courage, persuasion, influence, compassion. Inner power.',
  'Forza, coraggio, persuasione, influenza, compassione. Potere interiore.',
  'Inner strength, self-doubt, low energy, raw emotion.',
  'Forza interiore, insicurezza, poca energia, emozioni grezze.'),
(9, 'The Hermit', 'L''Eremita', 'major', NULL, 9, NULL,
  ARRAY['soul-searching', 'introspection', 'inner guidance', 'solitude'],
  ARRAY['ricerca interiore', 'introspezione', 'guida interiore', 'solitudine'],
  'Soul-searching, introspection, being alone, inner guidance.',
  'Ricerca interiore, introspezione, stare da soli, guida interiore.',
  'Isolation, loneliness, withdrawal from others.',
  'Isolamento, solitudine, ritiro dagli altri.'),
(10, 'Wheel of Fortune', 'La Ruota della Fortuna', 'major', NULL, 10, NULL,
  ARRAY['good luck', 'karma', 'life cycles', 'destiny', 'turning point'],
  ARRAY['fortuna', 'karma', 'cicli della vita', 'destino', 'punto di svolta'],
  'Good luck, karma, life cycles, destiny, a turning point.',
  'Fortuna, karma, cicli della vita, destino, punto di svolta.',
  'Bad luck, resistance to change, breaking cycles.',
  'Sfortuna, resistenza al cambiamento, rompere i cicli.'),
(11, 'Justice', 'La Giustizia', 'major', NULL, 11, NULL,
  ARRAY['justice', 'fairness', 'truth', 'cause and effect', 'law'],
  ARRAY['giustizia', 'equità', 'verità', 'causa ed effetto', 'legge'],
  'Justice, fairness, truth, cause and effect, law.',
  'Giustizia, equità, verità, causa ed effetto, legge.',
  'Unfairness, lack of accountability, dishonesty.',
  'Ingiustizia, mancanza di responsabilità, disonestà.'),
(12, 'The Hanged Man', 'L''Appeso', 'major', NULL, 12, NULL,
  ARRAY['pause', 'surrender', 'letting go', 'new perspectives'],
  ARRAY['pausa', 'resa', 'lasciare andare', 'nuove prospettive'],
  'Pause, surrender, letting go, new perspectives. Seeing things differently.',
  'Pausa, resa, lasciare andare, nuove prospettive. Vedere le cose diversamente.',
  'Delays, resistance, stalling, indecision.',
  'Ritardi, resistenza, temporeggiamento, indecisione.'),
(13, 'Death', 'La Morte', 'major', NULL, 13, NULL,
  ARRAY['endings', 'change', 'transformation', 'transition'],
  ARRAY['fine', 'cambiamento', 'trasformazione', 'transizione'],
  'Endings, change, transformation, transition. Letting go of the old.',
  'Fine, cambiamento, trasformazione, transizione. Lasciare andare il vecchio.',
  'Resistance to change, personal transformation, inner purging.',
  'Resistenza al cambiamento, trasformazione personale, purificazione interiore.'),
(14, 'Temperance', 'La Temperanza', 'major', NULL, 14, NULL,
  ARRAY['balance', 'moderation', 'patience', 'purpose'],
  ARRAY['equilibrio', 'moderazione', 'pazienza', 'scopo'],
  'Balance, moderation, patience, purpose. Finding middle ground.',
  'Equilibrio, moderazione, pazienza, scopo. Trovare un punto di mezzo.',
  'Imbalance, excess, self-healing, re-alignment.',
  'Squilibrio, eccesso, auto-guarigione, riallineamento.'),
(15, 'The Devil', 'Il Diavolo', 'major', NULL, 15, NULL,
  ARRAY['shadow self', 'attachment', 'addiction', 'restriction'],
  ARRAY['ombra', 'attaccamento', 'dipendenza', 'restrizione'],
  'Shadow self, attachment, addiction, restriction, sexuality.',
  'Ombra, attaccamento, dipendenza, restrizione, sessualità.',
  'Releasing limiting beliefs, exploring dark thoughts, detachment.',
  'Liberare credenze limitanti, esplorare pensieri oscuri, distacco.'),
(16, 'The Tower', 'La Torre', 'major', NULL, 16, NULL,
  ARRAY['sudden change', 'upheaval', 'chaos', 'revelation', 'awakening'],
  ARRAY['cambiamento improvviso', 'sconvolgimento', 'caos', 'rivelazione', 'risveglio'],
  'Sudden change, upheaval, chaos, revelation, awakening.',
  'Cambiamento improvviso, sconvolgimento, caos, rivelazione, risveglio.',
  'Personal transformation, fear of change, averting disaster.',
  'Trasformazione personale, paura del cambiamento, evitare il disastro.'),
(17, 'The Star', 'La Stella', 'major', NULL, 17, NULL,
  ARRAY['hope', 'faith', 'purpose', 'renewal', 'spirituality'],
  ARRAY['speranza', 'fede', 'scopo', 'rinnovamento', 'spiritualità'],
  'Hope, faith, purpose, renewal, spirituality. Inspiration.',
  'Speranza, fede, scopo, rinnovamento, spiritualità. Ispirazione.',
  'Lack of faith, despair, self-trust issues, disconnection.',
  'Mancanza di fede, disperazione, problemi di fiducia in sé, disconnessione.'),
(18, 'The Moon', 'La Luna', 'major', NULL, 18, NULL,
  ARRAY['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
  ARRAY['illusione', 'paura', 'ansia', 'subconscio', 'intuizione'],
  'Illusion, fear, anxiety, subconscious, intuition. Things are not as they seem.',
  'Illusione, paura, ansia, subconscio, intuizione. Le cose non sono come sembrano.',
  'Release of fear, repressed emotion, inner confusion.',
  'Liberazione dalla paura, emozioni represse, confusione interiore.'),
(19, 'The Sun', 'Il Sole', 'major', NULL, 19, NULL,
  ARRAY['positivity', 'fun', 'warmth', 'success', 'vitality'],
  ARRAY['positività', 'divertimento', 'calore', 'successo', 'vitalità'],
  'Positivity, fun, warmth, success, vitality. Joy and celebration.',
  'Positività, divertimento, calore, successo, vitalità. Gioia e celebrazione.',
  'Inner child, feeling down, overly optimistic.',
  'Bambino interiore, sentirsi giù, eccessivamente ottimista.'),
(20, 'Judgement', 'Il Giudizio', 'major', NULL, 20, NULL,
  ARRAY['judgement', 'rebirth', 'inner calling', 'absolution'],
  ARRAY['giudizio', 'rinascita', 'chiamata interiore', 'assoluzione'],
  'Judgement, rebirth, inner calling, absolution. Self-evaluation.',
  'Giudizio, rinascita, chiamata interiore, assoluzione. Auto-valutazione.',
  'Self-doubt, inner critic, ignoring the call.',
  'Insicurezza, critico interiore, ignorare la chiamata.'),
(21, 'The World', 'Il Mondo', 'major', NULL, 21, NULL,
  ARRAY['completion', 'integration', 'accomplishment', 'travel'],
  ARRAY['completamento', 'integrazione', 'realizzazione', 'viaggio'],
  'Completion, integration, accomplishment, travel. Achievement.',
  'Completamento, integrazione, realizzazione, viaggio. Traguardo.',
  'Seeking personal closure, short-cuts, delays.',
  'Cercare chiusura personale, scorciatoie, ritardi.')
ON CONFLICT (id) DO NOTHING;