/*
  # Seed Minor Arcana - Swords Suit

  Inserts 14 Swords cards (Ace through King)
*/

INSERT INTO tarot_cards (id, name_en, name_it, arcana, suit, number, court, keywords_en, keywords_it, upright_meaning_en, upright_meaning_it, reversed_meaning_en, reversed_meaning_it) VALUES
(50, 'Ace of Swords', 'Asso di Spade', 'minor', 'swords', 1, NULL,
  ARRAY['breakthrough', 'clarity', 'sharp mind', 'truth'],
  ARRAY['svolta', 'chiarezza', 'mente acuta', 'verità'],
  'Breakthrough, clarity, sharp mind, truth. Mental clarity.',
  'Svolta, chiarezza, mente acuta, verità. Chiarezza mentale.',
  'Inner clarity, re-thinking an idea, clouded judgement.',
  'Chiarezza interiore, ripensare un''idea, giudizio offuscato.'),
(51, 'Two of Swords', 'Due di Spade', 'minor', 'swords', 2, NULL,
  ARRAY['difficult decisions', 'weighing options', 'impasse'],
  ARRAY['decisioni difficili', 'valutare le opzioni', 'impasse'],
  'Difficult decisions, weighing up options, an impasse, avoidance.',
  'Decisioni difficili, valutare le opzioni, impasse, evitamento.',
  'Indecision, confusion, information overload.',
  'Indecisione, confusione, sovraccarico di informazioni.'),
(52, 'Three of Swords', 'Tre di Spade', 'minor', 'swords', 3, NULL,
  ARRAY['heartbreak', 'emotional pain', 'sorrow', 'grief'],
  ARRAY['crepacuore', 'dolore emotivo', 'tristezza', 'lutto'],
  'Heartbreak, emotional pain, sorrow, grief, hurt.',
  'Crepacuore, dolore emotivo, tristezza, lutto, ferita.',
  'Negative self-talk, releasing pain, optimism, forgiveness.',
  'Dialogo interiore negativo, rilasciare il dolore, ottimismo, perdono.'),
(53, 'Four of Swords', 'Quattro di Spade', 'minor', 'swords', 4, NULL,
  ARRAY['rest', 'relaxation', 'meditation', 'contemplation'],
  ARRAY['riposo', 'relax', 'meditazione', 'contemplazione'],
  'Rest, relaxation, meditation, contemplation, recuperation.',
  'Riposo, relax, meditazione, contemplazione, recupero.',
  'Exhaustion, burn-out, deep contemplation, stagnation.',
  'Esaurimento, burn-out, contemplazione profonda, stagnazione.'),
(54, 'Five of Swords', 'Cinque di Spade', 'minor', 'swords', 5, NULL,
  ARRAY['conflict', 'disagreements', 'competition', 'defeat'],
  ARRAY['conflitto', 'disaccordi', 'competizione', 'sconfitta'],
  'Conflict, disagreements, competition, defeat, winning at all costs.',
  'Conflitto, disaccordi, competizione, sconfitta, vincere a tutti i costi.',
  'Reconciliation, making amends, past resentment.',
  'Riconciliazione, fare ammenda, risentimento passato.'),
(55, 'Six of Swords', 'Sei di Spade', 'minor', 'swords', 6, NULL,
  ARRAY['transition', 'change', 'rite of passage', 'releasing baggage'],
  ARRAY['transizione', 'cambiamento', 'rito di passaggio', 'liberarsi del bagaglio'],
  'Transition, change, rite of passage, releasing baggage.',
  'Transizione, cambiamento, rito di passaggio, liberarsi del bagaglio.',
  'Personal transition, resistance to change, unfinished business.',
  'Transizione personale, resistenza al cambiamento, affari incompiuti.'),
(56, 'Seven of Swords', 'Sette di Spade', 'minor', 'swords', 7, NULL,
  ARRAY['betrayal', 'deception', 'getting away with something', 'strategy'],
  ARRAY['tradimento', 'inganno', 'farla franca', 'strategia'],
  'Betrayal, deception, getting away with something, acting strategically.',
  'Tradimento, inganno, farla franca, agire strategicamente.',
  'Imposter syndrome, self-deceit, keeping secrets.',
  'Sindrome dell''impostore, auto-inganno, mantenere segreti.'),
(57, 'Eight of Swords', 'Otto di Spade', 'minor', 'swords', 8, NULL,
  ARRAY['imprisonment', 'entrapment', 'self-victimization'],
  ARRAY['prigionia', 'intrappolamento', 'auto-vittimizzazione'],
  'Imprisonment, entrapment, self-victimization. Negative thoughts.',
  'Prigionia, intrappolamento, auto-vittimizzazione. Pensieri negativi.',
  'Self-limiting beliefs, inner critic, releasing negative thoughts.',
  'Credenze auto-limitanti, critico interiore, liberare pensieri negativi.'),
(58, 'Nine of Swords', 'Nove di Spade', 'minor', 'swords', 9, NULL,
  ARRAY['anxiety', 'worry', 'fear', 'depression', 'nightmares'],
  ARRAY['ansia', 'preoccupazione', 'paura', 'depressione', 'incubi'],
  'Anxiety, worry, fear, depression, nightmares.',
  'Ansia, preoccupazione, paura, depressione, incubi.',
  'Inner turmoil, deep-seated fears, secrets, releasing worry.',
  'Tumulto interiore, paure profonde, segreti, liberare la preoccupazione.'),
(59, 'Ten of Swords', 'Dieci di Spade', 'minor', 'swords', 10, NULL,
  ARRAY['painful endings', 'deep wounds', 'betrayal', 'loss'],
  ARRAY['fine dolorosa', 'ferite profonde', 'tradimento', 'perdita'],
  'Painful endings, deep wounds, betrayal, loss, crisis.',
  'Fine dolorosa, ferite profonde, tradimento, perdita, crisi.',
  'Recovery, regeneration, resisting an inevitable end.',
  'Recupero, rigenerazione, resistere a una fine inevitabile.'),
(60, 'Page of Swords', 'Fante di Spade', 'minor', 'swords', NULL, 'page',
  ARRAY['new ideas', 'curiosity', 'thirst for knowledge', 'new communication'],
  ARRAY['nuove idee', 'curiosità', 'sete di conoscenza', 'nuova comunicazione'],
  'New ideas, curiosity, thirst for knowledge, new ways of communicating.',
  'Nuove idee, curiosità, sete di conoscenza, nuovi modi di comunicare.',
  'Self-expression, all talk and no action, haphazard action.',
  'Auto-espressione, tutto chiacchiere e niente fatti, azione casuale.'),
(61, 'Knight of Swords', 'Cavaliere di Spade', 'minor', 'swords', NULL, 'knight',
  ARRAY['ambitious', 'action-oriented', 'driven to succeed'],
  ARRAY['ambizioso', 'orientato all''azione', 'determinato al successo'],
  'Ambitious, action-oriented, driven to succeed, fast-thinking.',
  'Ambizioso, orientato all''azione, determinato al successo, pensiero veloce.',
  'Restless, unfocused, impulsive, burn-out.',
  'Irrequieto, non focalizzato, impulsivo, burn-out.'),
(62, 'Queen of Swords', 'Regina di Spade', 'minor', 'swords', NULL, 'queen',
  ARRAY['independent', 'unbiased judgement', 'clear boundaries'],
  ARRAY['indipendente', 'giudizio imparziale', 'confini chiari'],
  'Independent, unbiased judgement, clear boundaries, direct communication.',
  'Indipendente, giudizio imparziale, confini chiari, comunicazione diretta.',
  'Overly-emotional, easily influenced, bitchy, cold-hearted.',
  'Troppo emotivo, facilmente influenzabile, acido, cuore freddo.'),
(63, 'King of Swords', 'Re di Spade', 'minor', 'swords', NULL, 'king',
  ARRAY['mental clarity', 'intellectual power', 'authority', 'truth'],
  ARRAY['chiarezza mentale', 'potere intellettuale', 'autorità', 'verità'],
  'Mental clarity, intellectual power, authority, truth.',
  'Chiarezza mentale, potere intellettuale, autorità, verità.',
  'Inner truth, misuse of power, manipulation.',
  'Verità interiore, abuso di potere, manipolazione.')
ON CONFLICT (id) DO NOTHING;